// Run only against a disposable test backend. Browser mutations are verified through the real API.
const { chromium, expect } = require('playwright/test')
const fs = require('node:fs/promises')
const path = require('node:path')
const API = process.env.UX_API_URL || 'http://localhost:3099/api'
const WEB = process.env.UX_WEB_URL || 'http://localhost:5173'
const OUT = path.join(__dirname, 'ux-artifacts')
let checks = 0
function pass(name) { checks++; console.log('PASS', name) }
async function request(method, route, body, token) {
  const res = await fetch(API + route, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) })
  const text = await res.text()
  if (!res.ok) throw Error(`${route} ${res.status}: ${text}`)
  return text ? JSON.parse(text) : null
}
;(async () => {
  await fs.mkdir(OUT, { recursive: true })
  const browser = await chromium.launch()
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, timezoneId: 'Asia/Bangkok', reducedMotion: 'reduce' })
  await context.tracing.start({ screenshots: true, snapshots: true })
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', e => errors.push(String(e)))
  try {
    const registration = await request('POST', '/auth/register', { email: `life-ui-${Date.now()}@test.local`, name: 'มิน', password: 'life-planning-local123', lang: 'th' })
    const token = registration.accessToken
    const api = (method, route, body) => request(method, route, body, token)
    await api('POST', '/auth/onboarding', { trackingMode: 'plan', monthlySpendingLimit: 30000, timezone: 'Asia/Bangkok', lang: 'th' })
    const user = await api('GET', '/auth/me')
    await context.addInitScript(({ token, user }) => {
      localStorage.setItem('flo_token', token); localStorage.setItem('flo_user', JSON.stringify(user)); localStorage.setItem('flo_lang', 'en')
    }, { token, user })
    await page.goto(WEB + '/budget')
    const bills = page.getByRole('region', { name: 'Monthly and outstanding bills', exact: true })
    const goals = page.getByRole('region', { name: 'Something to look forward to', exact: true })
    await expect(bills).toBeVisible(); await expect(goals).toBeVisible()
    await expect(page.getByRole('button', { name: 'Where the money sits' })).toHaveCount(0)
    pass('monthly plan shows spending, bills and goals without a competing envelope plan')
    await bills.getByRole('button', { name: 'Add a monthly bill' }).click()
    await bills.getByLabel('Bill name', { exact: true }).fill('ค่าเช่าบ้าน')
    await bills.getByLabel('Amount (฿)', { exact: true }).fill('6000')
    await bills.getByLabel('Day due (1–31)', { exact: true }).fill('25')
    await bills.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(bills.getByText('ค่าเช่าบ้าน', { exact: true })).toBeVisible()
    const before = await api('GET', '/analytics/daily-brief')
    expect(before.unpaidBills).toBe(6000)
    pass('adding a bill through the form reserves it in the real daily allowance')
    await goals.getByRole('button', { name: 'Add a savings goal' }).click()
    await goals.getByLabel('What are you saving for?', { exact: true }).fill('ไปเที่ยวญี่ปุ่น')
    await goals.getByLabel('Target amount', { exact: true }).fill('30000')
    await goals.getByLabel('Saved so far', { exact: true }).fill('5000')
    const future = new Date(); future.setMonth(future.getMonth() + 5)
    await goals.getByLabel('Target date', { exact: true }).fill(future.toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' }))
    await goals.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(goals.getByRole('heading', { name: 'ไปเที่ยวญี่ปุ่น', exact: true })).toBeVisible()
    expect((await api('GET', '/analytics/balance')).totalBalance).toBe(0)
    pass('savings progress is stored without fabricating a transaction or changing the ledger')
    await page.evaluate(() => document.fonts.ready)
    await page.screenshot({ path: path.join(OUT, 'planning-desktop.png'), fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: path.join(OUT, 'planning-mobile.png'), fullPage: true })
    pass('desktop and mobile layouts fit without horizontal scrolling')
    await bills.getByRole('button', { name: 'Pay bill', exact: true }).click()
    await expect(bills.getByRole('button', { name: 'Already recorded? Link an expense' })).toBeVisible()
    await bills.getByRole('button', { name: 'Pay and record ฿6,000.00', exact: true }).dblclick()
    await expect(bills.getByText('Expense recorded', { exact: true })).toBeVisible()
    const paid = await api('GET', '/analytics/daily-brief')
    expect(paid.monthSpent).toBe(6000); expect(paid.safeToday).toBe(before.safeToday)
    expect((await api('GET', '/expenses')).length).toBe(1)
    pass('paying a bill records once and keeps the already-reserved daily amount stable')
    await goals.getByRole('button', { name: 'Edit ไปเที่ยวญี่ปุ่น', exact: true }).click()
    await goals.getByLabel('Saved so far', { exact: true }).fill('30000')
    await goals.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(goals.getByText('Goal reached', { exact: true })).toBeVisible()
    pass('progress can be updated to a completed goal')
    const plan = await api('GET', '/planning')
    await api('DELETE', `/expenses/${plan.bills[0].expenseId}`)
    const cats = await api('GET', '/categories')
    await api('POST', '/expenses', { type: 'expense', categoryId: cats.find(c => c.type === 'expense').id, amount: 5900, note: 'จ่ายเองแล้ว', occurredAt: new Date().toISOString() })
    await page.reload()
    await bills.getByRole('button', { name: 'Pay bill', exact: true }).click()
    await bills.getByRole('button', { name: 'Already recorded? Link an expense' }).click()
    const expense = (await api('GET', '/expenses'))[0]
    await bills.getByLabel('Choose this month’s expense').selectOption(expense.id)
    await bills.getByRole('button', { name: 'Link without adding an expense' }).click()
    await expect(bills.getByText('Expense recorded', { exact: true })).toBeVisible()
    expect((await api('GET', '/expenses')).length).toBe(1)
    pass('an existing manual expense can pay the bill without duplication')
    await page.goto(WEB)
    await expect(page.getByRole('region', { name: 'Your money, at a glance.' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Wallets', exact: true })).toHaveCount(0)
    pass('home remains focused on the daily allowance and capture')
    await page.goto(WEB + '/wallets')
    await expect(page.getByText(/Envelopes divide the balance of transactions/)).toBeVisible()
    await page.getByRole('link', { name: /Go to my monthly plan/ }).click()
    await expect(bills).toBeVisible()
    pass('legacy envelope page explains its separate purpose and links back to the plan')
    await page.goto(WEB + '/settings')
    // Language control varies by layout; invoke the existing store via its visible button.
    await page.getByRole('button', { name: 'th', exact: true }).click()
    await page.getByRole('link', { name: 'แผนเงิน', exact: true }).click()
    await expect(page.getByRole('region', { name: 'บิลประจำและยอดค้างจ่าย', exact: true })).toBeVisible()
    await expect(page.getByRole('region', { name: 'เก็บเงินเพื่อสิ่งที่อยากทำ', exact: true })).toBeVisible()
    await page.evaluate(() => document.fonts.ready)
    await page.screenshot({ path: path.join(OUT, 'planning-mobile-th.png'), fullPage: true })
    await page.evaluate(() => document.documentElement.classList.add('dark'))
    await page.screenshot({ path: path.join(OUT, 'planning-mobile-dark.png'), fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    pass('Thai labels, dark theme and browser runtime are healthy')
    console.log(`${checks} planning browser checks passed`)
  } catch (err) {
    await page.screenshot({ path: path.join(OUT, 'planning-failure.png'), fullPage: true })
    throw err
  } finally {
    await context.tracing.stop({ path: path.join(OUT, 'planning-trace.zip') })
    await browser.close()
  }
})().catch(err => { console.error(err); process.exitCode = 1 })
